chore: add OOV abbreviation
pkeilbach/htwg-practical-nlp pull request #180
Opened 2024-11-22 15:58 UTC by SponsoredByPuma

2024-11-25 21:28 UTC, pkeilbach commented
Closes #179

2024-12-02 23:13 UTC, SponsoredByPuma commented
@pkeilbach I cannot assign you as a reviewer, but this could be ready to merge

2024-12-03 20:10 UTC, pkeilbach requested changes

2024-12-03 20:10 UTC, pkeilbach commented on docs/lectures/language_models.md
>  ## Out of Vocabulary Words
```suggestion
## Out of Vocabulary (OOV) Words
```

2024-12-03 20:11 UTC, pkeilbach approved these changes
LGTM! 🏅

2024-12-03 20:12 UTC, merged