Presentation open source LLMs
pkeilbach/htwg-practical-nlp pull request #58
Opened 2023-12-21 20:43 UTC by ka161heg

2023-12-22 17:55 UTC, pkeilbach commented on src/htwgnlp/preprocessing.py
please do not include any assignment code in your PR

2023-12-22 17:55 UTC, pkeilbach commented on docs/presentations/articles/assets/image-6.png
maybe an image like this one can be included from a public source?

2023-12-22 17:56 UTC, pkeilbach commented on docs/presentations/articles/assets/image-3.png
maybe an image like this one can be included from a public source?

2023-12-22 17:56 UTC, pkeilbach commented on docs/presentations/articles/assets/image-2.png
maybe an image like this one can be included from a public source?

2023-12-22 17:56 UTC, pkeilbach commented on docs/presentations/articles/assets/image-12.png
maybe an image like this one can be included from a public source?

2023-12-22 17:56 UTC, pkeilbach commented on docs/presentations/articles/assets/image-11.png
maybe an image like this one can be included from a public source?

2023-12-22 17:56 UTC, pkeilbach commented on docs/presentations/articles/assets/image-10.png
maybe an image like this one can be included from a public source?

2023-12-22 17:59 UTC, pkeilbach commented on docs/presentations/articles/OS_LLMs_Robert.md
would it be OK for you to provide the article in [English](https://pkeilbach.github.io/htwg-practical-nlp/presentations/presentations/#blog-article)? Sorry, I'm not sure if I mentioned this in lecture. Of course, it's totally acceptable to use a translation tool (please proof read it though)

2023-12-22 18:01 UTC, pkeilbach requested changes
Congrats on the first external PR in this repo, @ka161heg 🚀 🤩

Please see my comments and let me know if there are any questions! 

I also added a naming convention section for the filenames just now (#60), could you please adjust that?

2023-12-27 13:15 UTC, ka161heg commented on src/htwgnlp/preprocessing.py
Sorry, im not very familiar with git, so i didnt knewhow to do it properly.

2023-12-27 13:15 UTC, ka161heg commented on docs/presentations/articles/assets/image-6.png
included source under the image because i could not find proper URLS for the images.

2023-12-28 11:17 UTC, closed without merging