Add blog article for Virtual Assistants
pkeilbach/htwg-practical-nlp pull request #70
Opened 2024-01-16 09:16 UTC by MarcoMollo

I have also added an image folder for images to the blog post. Maybe other people can use that too

2024-01-16 20:33 UTC, pkeilbach commented on docs/presentations/articles/virtual_assistants.md
> +## Underlying Technologies - (rename, can be multiple)
The placeholder should be removed

```suggestion
## Underlying Technologies
```

2024-01-16 20:34 UTC, pkeilbach commented on docs/presentations/articles/virtual_assistants.md
> +<!-- feel free to add a profile link, remove the link, or remove the author information completely -->
you can remove this line

```suggestion
```

2024-01-16 20:35 UTC, pkeilbach commented on docs/presentations/images/Alexa.png:Zone.Identifier
What are those `Zone.Identifier` files for? I guess we can get rid of them

2024-01-16 20:36 UTC, pkeilbach commented on docs/presentations/images/Alexa.png
For the images, I added `docs/presentations/articles/assets` directory. You may need to pull in the latest changes.

2024-01-16 20:36 UTC, MarcoMollo commented on docs/presentations/images/Alexa.png:Zone.Identifier
Yes I think they create them self when copy pasting files from my windows file system to my Ubuntu

2024-01-16 20:37 UTC, MarcoMollo commented on docs/presentations/images/Alexa.png
Ok ill do it :)

2024-01-16 20:38 UTC, pkeilbach commented on docs/presentations/images/GoogleAssistant.png
please watch out the kebab case [naming conventions](https://pkeilbach.github.io/htwg-practical-nlp/presentations/presentations/#submission-via-pull-request) for the images: `google-assistant.png`

2024-01-16 20:39 UTC, pkeilbach requested changes
I have some first comments but looks already quite good, @MarcoMollo!

2024-01-17 07:48 UTC, pkeilbach commented on docs/presentations/articles/virtual_assistants.md
> +This articel will feature the underlying technology, how virtual assistants work, and how we as developers can use them.
```suggestion
This article will feature the underlying technology, how virtual assistants work, and how we, as developers, can use them.
```

2024-01-17 07:50 UTC, pkeilbach commented on docs/presentations/articles/virtual_assistants.md
> +Siri, Alexa and Google Assistant use Advanced automatic Speech Recognition technology to convert spoken language into text. To make this possible, ML models are trained on large data sets. The models
I wouldn't use it as a proper noun

```suggestion
Siri, Alexa and Google Assistant use Advanced automatic speech recognition technology to convert spoken language into text. To make this possible, ML models are trained on large data sets. The models are trained to recognize the patterns in the speech and convert them into text. The more data the model is trained on, the more accurate it becomes.
```

2024-01-17 07:51 UTC, pkeilbach commented on docs/presentations/articles/virtual_assistants.md
> +- You can integrate Google Assistant with [Actions on Google](https://developers.google.com/assistant/console?hl=de) for extending Assistant capabilities
Maybe a code snippet would be nice here!

2024-01-17 07:53 UTC, pkeilbach commented on docs/presentations/articles/virtual_assistants.md
> +![Hey Siri](./assets/hey-siri.png "Siri")
A little description for each image would be nice. Otherwise the layout looks also a bit weird

2024-01-17 07:54 UTC, pkeilbach commented on docs/presentations/articles/virtual_assistants.md
> +8. Privacy and Data Security
You can omit this list I'd say, it's generated in the outline to the right anyways

2024-01-17 07:54 UTC, pkeilbach commented on docs/presentations/articles/virtual_assistants.md
> +### Speech Roecognition
```suggestion
### Speech Recognition
```

2024-01-17 07:56 UTC, pkeilbach requested changes
Here are some further comments, but after that I think we are good to go!

2024-01-18 17:31 UTC, pkeilbach approved these changes
LGTM! 🚀

2024-01-18 17:32 UTC, merged